site_name: Cortside Guidelines
site_description: General guidelines by Cortside
site_url: https://www.cortside.com

repo_url: https://github.com/cortside/guidelines
edit_uri: edit/develop/docs

theme: readthedocs

# Build PDF & ePub
formats:
  - epub
  - pdf
 
nav:
- Architecture: architecture/README.md
- C#: csharp/README.md
- Scrum: scrum/README.md
- RESTful API Design: rest/README.md
- Template projects: webapistarter/README.md

# ci for docs
# https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/
